UPDATE  PERSONNE SET id_DEP = 1 WHERE id = 1 ;
UPDATE  PERSONNE SET id_DEP = 2 WHERE id = 2 ;
UPDATE  PERSONNE SET id_DEP = 3 WHERE id = 3 ;
UPDATE  PERSONNE SET id_DEP = 1 WHERE id = 4 ;
UPDATE  PERSONNE SET id_DEP = 2 WHERE id = 5 ;

